在代码0303中，我们发现代码单线程中定义的栈放在多线程中并不安全。
需要对接口做出改进，具体改进方案在书中第三章第二节。

相比于代码0303的定义，只保留了`push` `pop` `empty`三个接口:
```cpp
void push(T new_value);
std::shared_ptr<T> pop();
void pop(T& value);
bool empty() const;
```
接口越少，就越容易维护线程安全。

下面这个代码的结构表示结构体`empty_stack`继承了类`std::exception`
```cpp
struct empty_stack: std::exception
{
    const char* what() const throw();
};
```

对于` const char* what() const throw();`这个结构很有意思：
- 首先是返回值是`const char*`类型，函数名字是`what`。

- 成员函数的 `const` 修饰符：它表示这个成员函数不会修改所属对象的任何成员变量（除了那些被声明为 `mutable` 的成员变量）。这意味着你可以在 `const` 对象上调用这个函数。例如，如果有一个 `const empty_stack` 对象，你仍然可以调用它的 `what()` 函数来获取异常信息，因为 `what()` 不会改变对象的状态。

- `throw()` 是一个异常说明符，它表示这个函数不会抛出任何异常。在C++11之前的标准中，异常说明符用于指定一个函数可能抛出的异常类型。`throw()` 特别表示该函数不抛出任何异常。这在设计异常安全的代码时很有用，因为它向调用者保证了 `what()` 函数的调用不会引发新的异常，从而简化了异常处理逻辑。`throw()` 异常说明符用于声明一个函数不会抛出任何异常。这句话的意思是，当你在函数声明中加上` throw()`，你向调用者保证这个函数在执行过程中不会引发任何异常。这有助于调用者在编写代码时，不需要为这个函数的调用准备异常处理逻辑。

`what()` 函数的目的是提供异常的描述信息，而它自身在执行过程中不会引发新的异常。
```cpp
struct empty_stack : std::exception
{
    const char* what() const throw()
    {
        return "Stack is empty";
    }
};
```

异常处理：
当 `empty_stack` 异常被抛出时，程序的执行流程会立即转移到最近的 `catch` 块。如果当前函数没有 `catch` 块捕获这个异常，异常会继续向上层调用者传播，直到被某个 `catch` 块捕获或导致程序终止。
例如：
```cpp
try
{
    if (stack.empty())
    {
        throw empty_stack();
    }
    // 其他栈操作
}
catch (const empty_stack& e)
{
    std::cerr << "Exception caught: " << e.what() << std::endl;
    // 处理异常，例如可以在这里进行一些清理操作
}
```
在这个例子中，`empty_stack` 异常被 `catch` 块捕获，并且程序会继续执行 `catch` 块中的代码。
线程行为：
如果 `empty_stack` 异常被抛出并且没有被任何 `catch` 块捕获，程序会调用 `std::terminate()`，这通常会导致程序终止。在多线程环境中，如果一个线程抛出异常并且没有被捕获，整个程序可能会终止，具体行为取决于异常处理机制和运行时环境。
例如，如果在一个线程中抛出 `empty_stack` 异常并且没有被捕获，这个线程会终止，并且可能会导致整个程序终止，除非有全局的异常处理机制来捕获和处理这个异常。



